package com.bahadurkhail.welfare;

import android.os.Bundle;import android.graphics.Color;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import com.google.firebase.auth.FirebaseAuth;import com.google.firebase.firestore.FirebaseFirestore;import java.util.*;

public class MainActivity extends AppCompatActivity{
 LinearLayout root,body; FirebaseAuth auth; FirebaseFirestore db; final String ADMIN="wasifsher00788@gmail.com";
 int blue=Color.rgb(8,100,173);
 @Override public void onCreate(Bundle b){super.onCreate(b);auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance();showLogin();}
 TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.DKGRAY);t.setPadding(18,18,18,18);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(247,251,254));TextView h=tv("🤲  "+title,20);h.setTextColor(Color.WHITE);h.setBackgroundColor(blue);h.setPadding(20,25,20,25);root.addView(h);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(16,12,16,12);ScrollView sv=new ScrollView(this);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void showLogin(){base("Bahadur Khail Welfare Committee");body.addView(tv("Fi Sabeel Illah • خدمت • یکجہتی",16));EditText email=new EditText(this);email.setHint("Email");body.addView(email);EditText pass=new EditText(this);pass.setHint("Password");pass.setInputType(129);body.addView(pass);Button login=btn("LOGIN");body.addView(login);login.setOnClickListener(v->auth.signInWithEmailAndPassword(email.getText().toString().trim(),pass.getText().toString()).addOnSuccessListener(x->dashboard()).addOnFailureListener(e->Toast.makeText(this,"Login failed: "+e.getMessage(),Toast.LENGTH_LONG).show()));}
 void dashboard(){base("Bahadur Khail Welfare Committee");String em=auth.getCurrentUser().getEmail();body.addView(tv("Welcome 👋\n"+em,18));String[] names={"👥 Members","💰 Monthly Fund","🤲 Welfare Assistance","📢 Announcements","📊 Reports","⚙️ Organization"};String[] cols={"members","fund_payments","assistance","announcements","reports","organization"};for(int i=0;i<names.length;i++){Button b=btn(names[i]);body.addView(b);String c=cols[i];b.setOnClickListener(v->{if(c.equals("reports"))reports();else if(c.equals("organization"))organization();else collection(c);});}Button out=btn("Logout");body.addView(out);out.setOnClickListener(v->{auth.signOut();showLogin();});}
 void collection(String c){base(title(c));boolean admin=auth.getCurrentUser().getEmail().equalsIgnoreCase(ADMIN);if(admin){Button add=btn("+ Add New");body.addView(add);add.setOnClickListener(v->addRecord(c));}db.collection(c).get().addOnSuccessListener(q->{if(q.isEmpty())body.addView(tv("No records yet.",16));for(com.google.firebase.firestore.DocumentSnapshot d:q.getDocuments()){TextView t=tv(d.getData().toString(),15);body.addView(t);if(admin){Button del=btn("Delete");body.addView(del);del.setOnClickListener(v->d.getReference().delete().addOnSuccessListener(x->collection(c)));}}});Button back=btn("← Back");body.addView(back);back.setOnClickListener(v->dashboard());}
 String title(String c){if(c.equals("members"))return "Members";if(c.equals("fund_payments"))return "Monthly Fund";if(c.equals("assistance"))return "Welfare Assistance";return "Announcements";}
 void addRecord(String c){base("Add "+title(c));String[] hints=c.equals("members")?new String[]{"name","fatherName","phone","cnic","address","city","status"}:c.equals("fund_payments")?new String[]{"memberName","month","expected","paid","date","status"}:c.equals("assistance")?new String[]{"memberName","amount","purpose","date","status","notes"}:new String[]{"title","body","date"};ArrayList<EditText> es=new ArrayList<>();for(String h:hints){EditText e=new EditText(this);e.setHint(h);body.addView(e);es.add(e);}Button save=btn("Save Online");body.addView(save);save.setOnClickListener(v->{HashMap<String,Object> m=new HashMap<>();for(int i=0;i<hints.length;i++)m.put(hints[i],es.get(i).getText().toString());m.put("createdAt",new Date());db.collection(c).add(m).addOnSuccessListener(x->{Toast.makeText(this,"Saved online",Toast.LENGTH_SHORT).show();collection(c);});});}
 void reports(){base("Reports");for(String c:new String[]{"members","fund_payments","assistance","announcements"})db.collection(c).get().addOnSuccessListener(q->body.addView(tv(title(c)+": "+q.size(),17)));Button back=btn("← Back");body.addView(back);back.setOnClickListener(v->dashboard());}
 void organization(){base("Organization");body.addView(tv("Bahadur Khail Welfare Committee\nFi Sabeel Illah\nSalary module: Disabled\nAdmin: "+ADMIN,17));Button back=btn("← Back");body.addView(back);back.setOnClickListener(v->dashboard());}
}
