package com.bahadurkhail.welfare;

import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;
import com.google.firebase.auth.*;import com.google.firebase.firestore.*;import java.text.*;import java.util.*;

public class MainActivity extends AppCompatActivity {
 static final String ADMIN="wasifsher00788@gmail.com"; FirebaseAuth auth; FirebaseFirestore db; FrameLayout content; boolean isAdmin=false; LinearLayout root;
 int blue=Color.rgb(8,100,173);
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);content=findViewById(R.id.content);auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance(); if(auth.getCurrentUser()==null) login(); else enter();}
 TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.DKGRAY);t.setPadding(6,8,6,8);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void login(){content.removeAllViews(); LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER_HORIZONTAL);box.setPadding(20,40,20,20); ImageView im=new ImageView(this);im.setImageResource(R.drawable.logo);box.addView(im,new LinearLayout.LayoutParams(-1,180)); TextView h=tv("Admin / User Login",24);h.setTextColor(blue);h.setGravity(17);box.addView(h); EditText email=new EditText(this);email.setHint("Email");email.setInputType(33);box.addView(email); EditText pass=new EditText(this);pass.setHint("Password");pass.setInputType(129);box.addView(pass); Button b=btn("LOGIN");box.addView(b); TextView note=tv("Your data is stored online in Firebase.\nAdmin: "+ADMIN,13);box.addView(note);b.setOnClickListener(v->{String e=email.getText().toString().trim(),p=pass.getText().toString(); if(e.isEmpty()||p.isEmpty()){toast("Email and password required");return;}auth.signInWithEmailAndPassword(e,p).addOnSuccessListener(x->enter()).addOnFailureListener(x->toast(x.getMessage()));});content.addView(box); }
 void enter(){FirebaseUser u=auth.getCurrentUser();isAdmin=u!=null&&ADMIN.equalsIgnoreCase(u.getEmail()); dashboard();}
 void dashboard(){content.removeAllViews(); root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(6,8,6,8); TextView role=tv(isAdmin?"👑 ADMIN MODE":"👤 VIEW ONLY MODE",16);role.setTextColor(isAdmin?Color.rgb(0,110,60):Color.DKGRAY);root.addView(role); Button m=btn("👥 Members");Button f=btn("💰 Monthly Fund");Button a=btn("🤲 Welfare Assistance");Button o=btn("📢 Announcements");Button r=btn("📊 Reports / Summary");Button out=btn("🔒 Logout");root.addView(m);root.addView(f);root.addView(a);root.addView(o);root.addView(r);root.addView(out);m.setOnClickListener(v->members());f.setOnClickListener(v->funds());a.setOnClickListener(v->assistance());o.setOnClickListener(v->announcements());r.setOnClickListener(v->summary());out.setOnClickListener(v->{auth.signOut();login();});content.addView(root);}
 void members(){list("Members","members",new String[]{"name","fatherName","phone","cnic","address","city","joinDate","status"},true);}
 void funds(){list("Monthly Fund","fund_payments",new String[]{"memberName","month","expected","paid","date","status"},true);}
 void assistance(){list("Welfare Assistance","assistance",new String[]{"memberName","amount","purpose","date","status","notes"},true);}
 void announcements(){list("Announcements","announcements",new String[]{"title","body","date"},true);}
 void list(String heading,String col,String[] fields,boolean canAdd){content.removeAllViews(); LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL); TextView h=tv("‹  "+heading,22);h.setTextColor(blue);h.setOnClickListener(v->dashboard());box.addView(h); if(isAdmin&&canAdd){Button add=btn("+ Add");box.addView(add);add.setOnClickListener(v->addDialog(heading,col,fields));} ScrollView sv=new ScrollView(this);LinearLayout rows=new LinearLayout(this);rows.setOrientation(LinearLayout.VERTICAL);sv.addView(rows);box.addView(sv,new LinearLayout.LayoutParams(-1,0,1));content.addView(box); db.collection(col).orderBy("date",Query.Direction.DESCENDING).limit(100).get().addOnSuccessListener(q->{for(DocumentSnapshot d:q.getDocuments()){TextView row=tv(formatDoc(d,fields),15);row.setBackgroundColor(Color.WHITE);rows.addView(row,new LinearLayout.LayoutParams(-1,-2));if(isAdmin){row.setOnLongClickListener(v->{confirmDelete(col,d.getId());return true;});}}});}
 String formatDoc(DocumentSnapshot d,String[] fs){StringBuilder s=new StringBuilder(); for(String f:fs){Object v=d.get(f);if(v!=null)s.append(cap(f)).append(": ").append(v).append("\n");}return s.toString();}
 String cap(String x){return x.substring(0,1).toUpperCase()+x.substring(1);}
 void addDialog(String heading,String col,String[] fields){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);ArrayList<EditText> es=new ArrayList<>();for(String f:fields){EditText e=new EditText(this);e.setHint(cap(f));l.addView(e);es.add(e);} new AlertDialog.Builder(this).setTitle("Add "+heading).setView(l).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{Map<String,Object> m=new HashMap<>();for(int i=0;i<fields.length;i++)m.put(fields[i],es.get(i).getText().toString()); if(!m.containsKey("date")||String.valueOf(m.get("date")).isEmpty())m.put("date",today());db.collection(col).add(m).addOnSuccessListener(x->{toast("Saved online");list(heading,col,fields,true);}).addOnFailureListener(x->toast(x.getMessage()));}).show();}
 void confirmDelete(String col,String id){if(!isAdmin)return;new AlertDialog.Builder(this).setTitle("Delete record?").setMessage("This cannot be undone.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->db.collection(col).document(id).delete().addOnSuccessListener(x->toast("Deleted"))).show();}
 void summary(){db.collection("members").get().addOnSuccessListener(m->{db.collection("fund_payments").get().addOnSuccessListener(f->{db.collection("assistance").get().addOnSuccessListener(a->{new AlertDialog.Builder(this).setTitle("Welfare Summary").setMessage("Members: "+m.size()+"\nFund records: "+f.size()+"\nAssistance records: "+a.size()+"\n\nOnline database: Connected").setPositiveButton("OK",null).show();});});});}
 String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
